### ISSUE TITLE
Search functionality.

### ISSUE THREAD

**Issue by redacuve** [Dandush03/google-homepage#1]
You did an awesome job!, I think you can add to your page a full functionality adding this:
-- On your form, you can make the action to "http://www.google.com/search"
-- Add to your form the method "GET"
-- Add a name to the input, name="q"
And try to search for anything.

**Comment by Dandush03** [comment]
> You did an awesome job!, I think you can add to your page a full functionality adding this:
> -- On your form, you can make the action to "http://www.google.com/search"
> -- Add to your form the method "GET"
> -- Add a name to the input, name="q"
> And try to search for anything.

Fixed
